#! /bin/sh
#
### BEGIN INIT INFO
# Provides:          kd
# Required-Start:    $ALL
# Required-Stop:     
# Should-Start:      $ALL
# Should-Stop:      
# Default-Start:     3 4 5
# Default-Stop:
# Short-Description: 
# Description:       
### END INIT INFO

SERVER='ketonehu.com' /usr/local/bin/lcdd 2>&1 >/var/log/lcdd.log || true
/usr/local/bin/showips

